---
title: "Marking Scheme"
author: "K. Govindaraju"
date: "14 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 1

15 marks.  Each section is worth 5 marks.

1(a) Easy marks.  I expect most will get the explanation right.

1(b) Volunteer screening and its implication on the quality of the sample must be discussed.  I expect many to miss this.

1(c) Some may not discuss sampling errors in depth.  


## Question 2

35 marks. 7 marks for each section

Any two or three relevant graphs (except for section d) = 3 marks 

- Good interpretation gets full marks.  

- Do not expect the same answer as in the solutions.

Main points that must be noted in the EDA are

1.	Only 3 variables are important and not all the five
2.	Diabetes grouping is done after collection of the data (using cluster analysis)
3.	Purpose of study is discriminate between overt and chemical diabetic cases as well as how this progression can occur.

Part 2d: summary can be even just quantiles. 

Part 2e: students can fully agree with the journal artilce conclusions. Mainly look for new graphs and interpreations/justifications.
